--- 
- 
  name: "Add a new user"
  user: 
    name: "{{ item }}"
    shell: /bin/bash
  with_items: 
    - rupesh
    - ray
- 
  authorized_key: 
    key: "{{ lookup('file', '../../../sshkeys/{{ user_name }}/id_rsa.pub') }}"
    state: present
    user: "{{ item }}"
  name: "Give SSH access"
  with_items: 
    - rupesh
    - ray
