---
dependencies: []

galaxy_info:
  author: Rupesh Nemade
  description: Passenger installation for Linux/UNIX.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - development
    - web
    - ruby
    - rails
    - passenger
    - nginx